### ISSUE TITLE
Tail-invoking host functions?

### ISSUE THREAD

**Issue by jacobmischka** [WebAssembly/tail-call#9]
Does this proposal include tail-calling of host functions? The spec seems to only mention regular non-return invoking of host functions, but I didn't see anywhere that it explicitly says it's not possible.

Thanks!

**Comment by rossberg** [comment]
You can call a host function with `return_call` and friends. But since the core spec cannot define what a host function actually is, there is no guarantee about the behaviour of that. It may behave as if that function is performing another non-tail call immediately. As a consequence, tail-calling host functions may not take up stack space.

An embedder spec might provide additional specification, though.

**Comment by rossberg** [comment]
I think this has been resolved.

**Comment by thibaudmichaud** [comment]
@rossberg We (V8) were discussing this, and we think there is an unresolved issue.
On one hand the tail-call spec does not guarantee tail-call behavior for host functions (according to the overview and to this thread)
On the other hand doing a tail-call is guaranteed to unwind the caller frame, because it has an observable effect on exception handling (https://github.com/WebAssembly/exception-handling/issues/249)

So if wasm tail-invokes a host function inside a try block, and the host function throws, can the exception be caught by the caller or not?
FWIW V8 unwinds the caller regardless of the import, so the exception is not catchable.

**Comment by rossberg** [comment]
V8 is right and matches the specified semantics.

The loose statement about not guaranteeing "tail-call behaviour" for host calls is perhaps a bit misleading in this context. What we meant by it is merely that there is no guarantee that a host call does not take up additional stack space in an implementation. In other words, it isn't a statement about semantics but only a clarification about the cost model.

The spec prescribes semantics, but has no formal cost model. But even if it did, it wouldn't be able to prescribe anything about what happens inside the host. So technically speaking, this informal statement is trivially true. (In particular, it is completely indistinguishable for Wasm whether a call to the host is a non-tail call, or it _is_ a tail call, but the host happens to implemented the callee by itself (regularly) calling to a third function. To state anything useful cross boundary, we'd need a fully worked out cost model for both sides together.)

Does that clear up your concerns?

**Comment by thibaudmichaud** [comment]
Thanks for the detailed explanation, Andreas! I think this clears it up.
I do find this statement a bit misleading. Even reading it as a statement about the (informal) cost model rather than a statement about the observable behavior: engines will have to unwind the caller frame to satisfy the observable behavior (in particular try/catch), so they will save one frame compared to a regular call, regardless of whether the target function is a host function or not, and how much space it uses itself.
But I see your point with the mutual tail-recursion between wasm and the host. Even if the host can tail-call back into wasm, we cannot guarantee that this would consume O(1) space asymptotically because of what can happen at the boundary.

**Comment by rossberg** [comment]
Well, in theory, an engine is free to take a different path for host calls and merely do certain cleanup (like uninstalling local exception handlers) before performing a (regular) call, which could all happen without unwinding the actual caller frame. In a calling convention where tail calls depend on callee cooperation, and host functions do not provide that, that may be a viable implementation option.
